app = "your-app-name"

[build]
  builder = "heroku/buildpacks:20"

[env]
  HOST = "0.0.0.0"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443